name: WASP's BenchSpy Go Tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    defaults:
      run:
        working-directory: wasp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'wasp/benchspy/**'
      - uses: cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31
        if: steps.changes.outputs.src == 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        if: steps.changes.outputs.src == 'true'
        run: |-
          nix develop -c make test_benchspy_race
